FROM node:22-alpine3.20 as dev

WORKDIR /app

CMD [ "yarn", "dev" ]

#FROM node:22-alpine3.20 as build
#
#WORKDIR /app
#
#COPY package*.json ./
#
#RUN yarn install
#
#COPY . .
#
#RUN yarn build
#
#CMD [ "yarn", "dev" ]
